version: '3.8'

services:
  app:
    build: .
    container_name: generacion-documentacion
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # Agrega aqu√≠ tus variables de entorno
    restart: unless-stopped
